clc,clear
h0=figure('menubar','none',...
    'position',[100 150 600 500],...
    'name','防弯器曲率计算器',...
    'NumberTitle','off');
h1=axes('parent',h0,...
    'position',[0.05 0.45 0.55 0.5],...
    'Xlim',[0 1],'ylim',[0 1],...
    'XTick',0:0.2:1,'YTick',0:0.1:1,...
    'visible','on');

s1=uicontrol('parent',h0,...
    'string','D1',...
    'fontsize',20,...
    'style','text',...
    'position',[370 430 80 40]);
s2=uicontrol('parent',h0,...
    'string','d1',...
    'fontsize',20,...
    'style','text',...
    'position',[370 380 80 40]);
s3=uicontrol('parent',h0,...
    'string','d2',...
    'fontsize',20,...
    'style','text',...
    'position',[370 330 80 40]);
s4=uicontrol('parent',h0,...
    'string','L1',...
    'fontsize',20,...
    'style','text',...
    'position',[370 280 80 40]);
s5=uicontrol('parent',h0,...
    'string','L2',...
    'fontsize',20,...
    'style','text',...
    'position',[370 230 80 40]);
s6=uicontrol('parent',h0,...
    'string','L3',...
    'fontsize',20,...
    'style','text',...
    'position',[370 180 80 40]);
s7=uicontrol('parent',h0,...
    'string','EIp',...
    'fontsize',20,...
    'style','text',...
    'position',[370 130 80 40]);
s8=uicontrol('parent',h0,...
    'string','Es',...
    'fontsize',20,...
    'style','text',...
    'position',[370 80 80 40]);
s9=uicontrol('parent',h0,...
    'string','F',...
    'fontsize',20,...
    'style','text',...
    'position',[170 130 80 40]);
s10=uicontrol('parent',h0,...
    'string','角度',...
    'fontsize',20,...
    'style','text',...
    'position',[170 80 80 40]);
s11=uicontrol('parent',h0,...
    'string','Maxκ',...
    'fontsize',20,...
    'style','text',...
    'position',[30 130 80 40]);

e1=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[470 430 80 40],...
    'string','',...
    'backgroundcolor','w');
e2=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[470 380 80 40],...
    'string','',...
    'backgroundcolor','w');
e3=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[470 330 80 40],...
    'string','',...
    'backgroundcolor','w');
e4=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[470 280 80 40],...
    'string','',...
    'backgroundcolor','w');
e5=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[470 230 80 40],...
    'string','',...
    'backgroundcolor','w');
e6=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[470 180 80 40],...
    'string','',...
    'backgroundcolor','w');
e7=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[470 130 80 40],...
    'string','',...
    'backgroundcolor','w');
e8=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[470 80 80 40],...
    'string','',...
    'backgroundcolor','w');
e9=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[270 130 80 40],...
    'string','',...
    'backgroundcolor','w');
e10=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[270 80 80 40],...
    'string','',...
    'backgroundcolor','w');
e11=uicontrol('parent',h0,...
    'style','edit',...
    'fontsize',18,...
    'horizontal','right',...
    'position',[30 80 80 40],...
    'string','',...
    'backgroundcolor','w');

p1=uicontrol('parent',h0,...
    'string','开始',...
    'fontsize',26,...
    'position',[30 20 100 50],...
    'callback',['max_k=eval(get(e11,''string''));',...
    'D1=eval(get(e1,''string''));',...
    'd1=eval(get(e2,''string''));',...
    'd2=eval(get(e3,''string''));',...
    'L1=eval(get(e4,''string''));',...
    'L2=eval(get(e5,''string''));',...
    'L3=eval(get(e6,''string''));',...
    'EIp=eval(get(e7,''string''));',...
    'Es=eval(get(e8,''string''));',...
    'F=eval(get(e9,''string''));',...
    'q=eval(get(e10,''string''));',...
    'main(max_k,D1,d1,d2,L1,L2,L3,EIp,Es,F,q);',...
    'grid on']);
    




